export enum Genre {
  ACTION = 'ACTION',
  COMEDY = 'COMEDY',
  DRAMA = 'DRAMA',
  ADVENTURE = 'ADVENTURE',
  HISTORICAL = 'HISTORICAL',
  FANTASY = 'FANTASY',
  HORROR = 'HORROR',
  MYSTERY = 'MYSTERY',
  ROMANCE = 'ROMANCE',
  SCI_FI = 'SCI-FI',
  THRILLER = 'THRILLER',
  WESTERN = 'WESTERN',
}
